### PR TITLE
feature: added user authentication

### PR DESCRIPTION
**Pull request by Jmlevick**
I'm using this driver on production and needed user authentication so I added this feature. I want to add more features but don't have time right now. Looking forward to collaborate with you.

P.S. Sorry if I didn't follow your style guide or something like that, any feedback will be appreciated.

### CODE REVIEW

**Comment by thaiat** [comment]
HI @Jmlevick 
thks for your PR, can you fix the lint issue that makes the build fail on travis

**Comment by Jmlevick** [comment]
Done, travis tests pass and fixed another bug I had... My team and I are using this module with the authentication addons and no problems

**Comment by thaiat** [comment]
ok last thing before i can merge, can you squash your commit and make sure your commit message is: `feat(app): add user authentication`

**Comment by Jmlevick** [comment]
I think I did it! Bit of a git noob here, so let me know how it goes and thanks for the patience, I'm learning quite a bit with this process.

**Comment by Jmlevick** [comment]
any updates?

**Comment by thaiat** [comment]
i just merged your changes

**Pull request merged**
